# Generated by Django 5.2.8 on 2025-11-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='lugar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
