# Generated by Django 5.2.8 on 2025-11-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_actividad_lugar_alter_actividad_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='lugar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
